name: bcrypt
description: This package use jBCrypt modified code to work with Dart VM.
version: 1.1.3
repository: https://github.com/ndesamuelmbah/dart-bcrypt
# homepage: https://github.com/astudilloalex/dart-bcrypt

environment:
  sdk: '>=3.2.2 < 4.0.0'
  
# dependencies:
#   path: ^1.8.0

# dev_dependencies:
#   test: ^1.25.8
dev_dependencies:
  flutter_test:
    sdk: flutter
