name: bcrypt
description: This package use jBCrypt modified code to work with Dart VM.
version: 1.1.3
repository: https://github.com/ndesamuelmbah/dart-bcrypt
# homepage: https://github.com/astudilloalex/dart-bcrypt

environment:
  sdk: '>=2.17.1 <3.0.0'
  
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.3
